/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc_gui_4a;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;

/**
 *
 * @author DonVuk14
 */

public class MAINwindow extends javax.swing.JFrame {
        Connection con = null;
        PreparedStatement stmt_selectAll=null;
        PreparedStatement stmt_selectAll2=null;
        ResultSet res_selectALL = null;
        ResultSet res_selectALL2 = null;

        
        PreparedStatement stmt_add = null;
        PreparedStatement stmt_add2 = null;
    /**
     * Creates new form MAINwindow
     */
    public MAINwindow() {
        initComponents();
        
        
         try{
        Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException ex){
            System.out.println("Datenbank kann nicht geladen werden");
            javax.swing.JOptionPane.showMessageDialog(this, "Datenbank kann nicht gelden werden");
            System.exit(1);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Server = new javax.swing.JLabel();
        Port = new javax.swing.JLabel();
        Connect = new javax.swing.JButton();
        Disconnect = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        aa = new javax.swing.JLabel();
        bb = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        pp = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtJOB = new javax.swing.JTextField();
        txtMGR = new javax.swing.JTextField();
        txtHIREDATE = new javax.swing.JTextField();
        AddEmployee = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSAL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCOMM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDEPTNO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        clearEmployee = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtGRADE = new javax.swing.JTextField();
        txtHOSAL = new javax.swing.JTextField();
        txtLOSAL = new javax.swing.JTextField();
        Addsalgrade = new javax.swing.JButton();
        Clearsalgrade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Server.setText("Server");

        Port.setText("Port");

        Connect.setText("Connect");
        Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectActionPerformed(evt);
            }
        });

        Disconnect.setText("Disconnect");
        Disconnect.setEnabled(false);
        Disconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisconnectActionPerformed(evt);
            }
        });

        jTextField1.setText("localhost");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("3306");

        aa.setText("ID:");

        bb.setText("ename:");

        cc.setText("JOB");

        dd.setText("MGR");

        pp.setText("HIREDATE:");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtMGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMGRActionPerformed(evt);
            }
        });

        AddEmployee.setText("Add employee");
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Custom SQL Statement for Select");

        jLabel1.setText("SAL:");

        txtSAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSALActionPerformed(evt);
            }
        });

        jLabel2.setText("COMM:");

        txtCOMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCOMMActionPerformed(evt);
            }
        });

        jLabel3.setText("DEPTNO:");

        jLabel4.setText("User:");

        jTextField6.setEditable(false);
        jTextField6.setText("root");

        jLabel5.setText("Password:");

        jTextField7.setEditable(false);

        jLabel7.setText("Database:");

        jTextField3.setEditable(false);
        jTextField3.setText("scott");

        clearEmployee.setText("Clear employee");
        clearEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEmployeeActionPerformed(evt);
            }
        });

        jLabel8.setText("Tabelle salgrade");

        jLabel9.setText("GRADE:");

        jLabel10.setText("HOSAL:");

        jLabel11.setText("LOSAL:");

        Addsalgrade.setText("Add salgrade");

        Clearsalgrade.setText("Clear salgrade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cc)
                            .addComponent(pp)
                            .addComponent(dd)
                            .addComponent(bb)
                            .addComponent(aa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(txtMGR)
                            .addComponent(txtHIREDATE)
                            .addComponent(txtJOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(txtName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clearEmployee)
                                .addGap(346, 346, 346))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddEmployee)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCOMM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSAL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDEPTNO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 463, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Server)
                    .addComponent(Port))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jTextField2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Disconnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Connect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtLOSAL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHOSAL, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Addsalgrade)
                            .addComponent(Clearsalgrade))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Server)
                    .addComponent(Connect)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Port)
                    .addComponent(Disconnect)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aa)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bb)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cc)
                            .addComponent(txtJOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dd)
                            .addComponent(txtMGR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp)
                            .addComponent(txtHIREDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearEmployee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCOMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDEPTNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddEmployee)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtGRADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Addsalgrade)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHOSAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clearsalgrade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtLOSAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectActionPerformed
        // TODO add your handling code here:
        
       
        try{
              con= DriverManager.getConnection("jdbc:mysql://localhost/scott", "root", "");
              Connect.setEnabled(false);
              Disconnect.setEnabled(true);
              jTextField1.setEnabled(false);
               }
        catch (SQLException ex){
                   System.out.println("Verbindung mit dem Datenbankserver" + "konnte nicht hergestellt werden");
                   javax.swing.JOptionPane.showMessageDialog(this, "Datenbank kann nicht gelden werden");
                    System.exit(1);
               }
        
        try{
             stmt_selectAll = con.prepareStatement("SELECT * FROM EMP");
             res_selectALL=stmt_selectAll.executeQuery();
             
             if(res_selectALL.next()){
                 int id = res_selectALL.getInt("EMPNO");
                 String ename = res_selectALL.getString("Ename");
                 String JOB = res_selectALL.getString("JOB");
                 int MGR = res_selectALL.getInt("MGR");
                 String HIREDATE = res_selectALL.getString("HIREDATE");
                 double SAL = res_selectALL.getInt("SAL");
                 double COMM = res_selectALL.getInt("COMM");
                 int DEPTNO = res_selectALL.getInt("DEPTNO");
                 
                 txtID.setText(""+id);
                 txtName.setText(ename);
                 txtJOB.setText(JOB);
                 txtMGR.setText(""+MGR);
                 txtHIREDATE.setText(HIREDATE);
                 txtSAL.setText(""+SAL);
                 txtCOMM.setText(""+COMM);
                 txtDEPTNO.setText(""+DEPTNO);
                
             } 
             stmt_selectAll2 = con.prepareStatement("SELECT * FROM salgrade");
              if(res_selectALL2.next()){
                int GRADE = res_selectALL2.getInt("GRADE");
                int HOSAL = res_selectALL2.getInt("HOSAL");
                int LOSAL = res_selectALL2.getInt("LOSAL");
                 
                    "INSERT INTO salgrade(GRADE, HOSAL, LOSAL) values(?,?,?)"
        );
         }catch(SQLException ex){
             System.out.println("error connecting");
         }
        }
    }//GEN-LAST:event_ConnectActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void DisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectActionPerformed
        // TODO add your handling code here:
        try{
              con.close();
              Connect.setEnabled(true);
              Disconnect.setEnabled(false); 
              jTextField1.setEnabled(true);
               }catch (SQLException ex){
                   System.out.println("Verbindung mit dem Datenbankserver" + "konnte nicht hergestellt werden");
                   javax.swing.JOptionPane.showMessageDialog(this, "Datenbank kann nicht gelden werden");
                    System.exit(1);
               }
    }//GEN-LAST:event_DisconnectActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMGRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMGRActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
                 if(res_selectALL.next()){
                 int id = res_selectALL.getInt("EMPNO");
                 String ename = res_selectALL.getString("Ename");
                 String JOB = res_selectALL.getString("JOB");
                 int MGR = res_selectALL.getInt("MGR");
                 String HIREDATE = res_selectALL.getString("HIREDATE");
                 double SAL = res_selectALL.getInt("SAL");
                 double COMM = res_selectALL.getInt("COMM");
                 int DEPTNO = res_selectALL.getInt("DEPTNO");
                 
                 txtID.setText(""+id);
                 txtName.setText(ename);
                 txtJOB.setText(JOB);
                 txtMGR.setText(""+MGR);
                 txtHIREDATE.setText(HIREDATE);
                 txtSAL.setText(""+SAL);
                 txtCOMM.setText(""+COMM);
                 txtDEPTNO.setText(""+DEPTNO);
                 
             }else{
                     res_selectALL.beforeFirst();
                 }
         }catch(SQLException ex){
             System.out.println("konnte nicht gemacht werden");
             javax.swing.JOptionPane.showMessageDialog(this,"Select kann nicht gemacht werden");
         }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
                 if(res_selectALL.previous()){
                 int id = res_selectALL.getInt("EMPNO");
                 String ename = res_selectALL.getString("Ename");
                 String JOB = res_selectALL.getString("JOB");
                 int MGR = res_selectALL.getInt("MGR");
                 String HIREDATE = res_selectALL.getString("HIREDATE");
                 double SAL = res_selectALL.getInt("SAL");
                 double COMM = res_selectALL.getInt("COMM");
                 int DEPTNO = res_selectALL.getInt("DEPTNO");
                 
                 txtID.setText(""+id);
                 txtName.setText(ename);
                 txtJOB.setText(JOB);
                 txtMGR.setText(""+MGR);
                 txtHIREDATE.setText(HIREDATE);
                 txtSAL.setText(""+SAL);
                 txtCOMM.setText(""+COMM);
                 txtDEPTNO.setText(""+DEPTNO);
                 
             }else{
                     res_selectALL.afterLast();
                 }
         }catch(SQLException ex){
             System.out.println("konnte nicht gemacht werden");
             javax.swing.JOptionPane.showMessageDialog(this,"Select kann nicht gemacht werden");
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtID.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
        try{
        stmt_add.setString(1, txtName.getText());
        stmt_add.setString(2,txtJOB.getText());
        int mgr= Integer.parseInt(txtMGR.getText());
        stmt_add.setInt(3, mgr);        
        
        
        stmt_add.setString(4, txtHIREDATE.getText());
        
        double sal = Double.parseDouble(txtSAL.getText());
        stmt_add.setDouble(5, sal);
        
        double comm = Double.parseDouble(txtCOMM.getText());
        stmt_add.setDouble(6, comm);
        
        int deptno = Integer.parseInt(txtDEPTNO.getText());
        stmt_add.setInt(7, deptno);
        
        int rows_changed = stmt_add.executeUpdate();
        
        if(rows_changed > 0){
                javax.swing.JOptionPane.showMessageDialog(this, "Angestellter wurde eingefuegt");
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Angestellter wurde nicht eingefuegt");
        }
        stmt_add.executeUpdate();
        
        }catch(SQLException ex){
            ex.printStackTrace();
            System.out.println("konnte nicht gemacht werden");
            javax.swing.JOptionPane.showMessageDialog(this,"Select kann nicht gemacht werden");
        }
        //Werte von Textfields in Variablen speichern
        //Parameter an ein ADD statement binden
        //Statement ausfuehren
        //Fehlermeldung, wenn es kein Add gegeben hat.
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void txtSALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSALActionPerformed

    private void txtCOMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCOMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCOMMActionPerformed

    private void clearEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEmployeeActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtSAL.setText("");
        txtJOB.setText("");
        txtCOMM.setText("");
        txtMGR.setText("");
        txtHIREDATE.setText("");
        txtDEPTNO.setText("");
        
        javax.swing.JOptionPane.showMessageDialog(this, "Clear gemacht.");
    }//GEN-LAST:event_clearEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAINwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAINwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAINwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAINwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINwindow().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton Addsalgrade;
    private javax.swing.JButton Clearsalgrade;
    private javax.swing.JButton Connect;
    private javax.swing.JButton Disconnect;
    private javax.swing.JLabel Port;
    private javax.swing.JLabel Server;
    private javax.swing.JLabel aa;
    private javax.swing.JLabel bb;
    private javax.swing.JLabel cc;
    private javax.swing.JButton clearEmployee;
    private javax.swing.JLabel dd;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel pp;
    private javax.swing.JTextField txtCOMM;
    private javax.swing.JTextField txtDEPTNO;
    private javax.swing.JTextField txtGRADE;
    private javax.swing.JTextField txtHIREDATE;
    private javax.swing.JTextField txtHOSAL;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJOB;
    private javax.swing.JTextField txtLOSAL;
    private javax.swing.JTextField txtMGR;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSAL;
    // End of variables declaration//GEN-END:variables
}
